### ISSUE TITLE
Can't start OTR session from Android phone

### ISSUE THREAD

**Issue by asherchayyim** [mmb/weechat-otr#102]
I have ChatSecure installed on my Android phone.
Whenever I press the "Start encryption" menu-button in the conversation, nothing happens, no matter how many times I try. OTR just won't start.

I am using a "xmpp.jp" account to communicate with my friends who are also on that server.
By "communicate" I mean 1-on-1 chats, no groups.
I am also using Pidgin on my PC. In Pidgin, for example, I am able to start "encrypted" conversations with any of my friends, however, with the same account and same friends, I am unable to start encrypted chat on Android ChatSecure. 

I have tried logging off PC and then logging on ChatSecure. That helped SOMETIMES. Sometimes it didn't. SO I'm not sure if they are related, because SOMETIMES ChatSecure is unable to start encrypted chats even when I am NOT logged in with the same account on any other device.

Please fix OTR in ChatSecure.
Thank you.

(ChatSecure 14.0.9, Android 4.2.2)

**Comment by tribut** [comment]
Could you please clarify whether you're seeing this issue while talking to a peer using weechat and weechat's otr.py? If this is a ChatSecure/Android issue, please report it there: https://dev.guardianproject.info/projects/gibberbot/issues/new

**Comment by asherchayyim** [comment]
I have mistakenly posted the bug here. My apologies. I'll post it in the appropriate thread. Please close this ticket here. thank you.

**Comment by Mikaela** [comment]
@asherchayyim you should have the close button under comment box as you have opened the issue.
