### ISSUE TITLE
Outbound privmsgs arguments sometimes do not contain a space.

### ISSUE THREAD

**Issue by mmb** [mmb/weechat-otr#106]
```
23:40:22 :! otr !: | Traceback (most recent call last):                            
23:40:22           |   File "/home/user/.weechat/python/autoload/otr.py", line 1165, in
                   | message_out_cb                                                
23:40:22           |     parsed = parse_irc_privmsg(PYVER.to_unicode(string))           
23:40:22           |   File "/home/user/.weechat/python/autoload/otr.py", line 323, in   
                   | parse_irc_privmsg                                             
23:40:22           |     weechat_result['arguments']).split(' ', 1)                
23:40:22           | ValueError: need more than 1 value to unpack 
```

Add better error reporting to determine the root cause.

**Comment by tribut** [comment]
That seems like an old version. Do we know which one?
I've never seen this problem in ages (I think we fixed a bug regarding `.split()` once?), is it maybe something that only happens with a specific server?

**Comment by Mikaela** [comment]
I was seeing this often with the version that is in `/script`.  I cannot remember seeing this lately on OTR.py.

**Comment by mmb** [comment]
@tribut Could be WeeChat < 1.0, which is when your fix for http://savannah.nongnu.org/bugs/?41640 went in.

**Comment by mmb** [comment]
If anyone sees this again please re-open with the WeeChat version and the script version.
