### ISSUE TITLE
"Unencrypted message received: " prefix on messages received in chat channel from user with active OTR conversation

### ISSUE THREAD

**Issue by manasb** [mmb/weechat-otr#107]
Hello,

I am using weechat 1.1 with weechat-otr 1.5.0.
When I am in an OTR conversation with a contact and this contact says something in a chat channel, the message is prefixed with "Unencrypted message received: "
I have tried latest git unstable and the issue still remains. This phrase appears on line 1170 of weechat_otr.py. Removing the except that prints this message appears to fix the issue but causes other problems too, so that is not a viable workaround.
Please let me know if you require further information.

Thanks,
Manas

**Comment by tribut** [comment]
Unfortunately, I can't reproduce this. Here is what I did:

 * Connect to freenode using two instances of weechat
 * Establish an OTR session in a query using `/otr start`
 * Both clients join a channel, send messages
 * No messages in the channel are prefixed.

Can you give detailed instruction what you did?

**Comment by manasb** [comment]
Hm there is an option I changed. I think that is what caused it, I assumed it was only for private messages but it seems it applies to all messages from that person:

otr.policy.[server].[me].[them].require_encryption

**Comment by Mikaela** [comment]
I have require_encryption set with one person and for me it seems to only affect their queries.

**Comment by mmb** [comment]
@manasb If you could `/set otr.general.debug on` and add the relevant 'message_in_cb' line from the OTR debug buffer that might help.

**Comment by manasb** [comment]
(u'message_in_cb', '', 'irc_in_PRIVMSG', '[network]', ':[ident]![user]@[hostname] PRIVMSG #[channel] :[message]')

This is the 'message_in_cb' line for the received message in a chat channel that is prefixed with "Unencrypted message received: " while in an OTR conversation with the sender.

**Comment by mmb** [comment]
The message looks normal. What does the "parsed message" line immediately below it in the debug log say?

Are there any spaces or other weird characters in the channel name?

Feel free to email me at matthewm@boedicker.org if you do not want to post details here.

**Comment by mmb** [comment]
This was in the latest master and was caused by the server not returning CHANTYPES and STATUSMSG. We will fix this by falling back to default values for channel prefixes in this case. Thanks for finding this bug.
