### ISSUE TITLE
Per-network default policies

### ISSUE THREAD

**Issue by Mikaela** [mmb/weechat-otr#120]
I use BItlBee with it's own OTR, because WeeChat captures my queries and I cannot read messages which I receive on phone as they are encrypted. If I start OTR with BitlBee, WeeChat-OTR captures the discussion to it's own key.

It would help me a lot if I could blacklist BitlBee so OTR is never used there.

**Comment by tribut** [comment]
I was almost sure we already had a bug request for this, but I can't find it. We should support

    otr.policy.servername.*

for network-wide defaults. Seems also straightforward to integrate into `/otr policy`.

**Comment by mmb** [comment]
Agreed this seems like an easy change to IrcContext.getPolicy().

We should give precedence to individual policies so you could set a policy for a network but also override the network setting for an individual user.

Using `*` seems like the most obvious option but I did some testing and it conflicts with WeeChat's interpretation of `*` in `/set`.
