### ISSUE TITLE
Think about notices too with whitespace tag

### ISSUE THREAD

**Issue by Mikaela** [mmb/weechat-otr#122]
If I have understood correctly, OTR.py appends the whitespace tag to end of messages as long as the other party has either initiated OTR or sent PRIVMSG without the tag.

Talking with bots and services that follow the RFC on notices reply with notices instead of PRIVMSGs causing OTR.py always append the whitespace tag. It doesn't matter with intelligent bots/services which just silently ignore it, but more stupid ones...

I thought I would open this issue for considering if notices should also be handled that way or if there are legitimate cases for not handling them so.

**Comment by mmb** [comment]
Have you tried setting `otr.general.no_send_tag_regex` or the individual send_tag policies on the bot nicks?

The script does not see notices because it only subscribes to PRIVMSG hooks.

**Comment by Mikaela** [comment]
No, as it's not so big issue.

I see.
