### ISSUE TITLE
Nicks should be case-insensitive

### ISSUE THREAD

**Issue by tribut** [mmb/weechat-otr#124]
A user in #otr on oftc reported errors from potr:

    Hi! I am trying to communicate with a peer using python-otr and weechat. 
    The peer is also using weechat-otr and while both sides see each other as
    authenticated and encrypted, messages are shown as unencrypted in the UI.
    In the console I see a lot of messages like these:
     python: stdout/stderr: ERROR:potr.crypt:bad state (1) for Signature  
    how can I debug this further?

This appears to happen when one of the peers uses a non-canonical capitalization of the other peer's nick. I could reproduce this by changing my nick from "felix2" to "Felix2" during a conversation. This is a bad bug, because `/otr start` appears to work ("Private conversation has been refreshed"), yet the messages are sent **unencrypted**.

**Comment by mmb** [comment]
Could anyone who experienced this bug try whatever they were doing to reproduce it with the new version?

**Comment by tribut** [comment]
From the reporter:

    thanks that has fixed it

**Comment by Mikaela** [comment]
I wonder if this could be the cause of https://github.com/mmb/weechat-otr/issues/121 as the symptoms are similar. I haven't seen Drunkwizard in a long time though.
