### ISSUE TITLE
InvalidParameterError during OTR session with peer using pidgin

### ISSUE THREAD

**Issue by mmb** [mmb/weechat-otr#125]
https://transfer.sh/quJ4Q/weechat-otr-python-errors.png

http://dpaste.com/2D3YV6M

**Comment by Mikaela** [comment]
The files would be more easily available in the future if they were pasted in to the issue directly.

`![optional description](https://transfer.sh/quJ4Q/weechat-otr-python-errors.png)`
![optional description](https://transfer.sh/quJ4Q/weechat-otr-python-errors.png)

and within block starting with \`\`\` and new line and ending to new line and \`\`\`.

```
ncurses: 5.9 (patch 20110404)
gcrypt: 1.6.3
gnutls: 3.3.17
curl: 7.43.0
zlib: 1.2.8
aspell: aspell (?)
python: 2.7.10
perl: 5.20.2
```

**Comment by mmb** [comment]
The user reports that the peer was using both ZNC OTR and WeeChat OTR at the same time. Also more than one client was connected to ZNC. It seems probable that that could have caused the issue. Please open a new issue if this happens again.
