### ISSUE TITLE
non-ascii chars in nick

### ISSUE THREAD

**Issue by l2dy** [mmb/weechat-otr#133]
```
=!=	python: wrong arguments for function "config_get" (script: otr)
	python: stdout/stderr: Versions: weechat-otr 1.9.0, potr 1.0.0-final, Python 2.7.13, WeeChat 1.8
	python: stdout/stderr: Traceback (most recent call last):
	python: stdout/stderr:   File "$HOME/.weechat/python/autoload/otr.py", line 1359, in command_cb
	python: stdout/stderr:     context.previous_log_level = context.disable_logging()
	python: stdout/stderr:   File "$HOME/.weechat/python/autoload/otr.py", line 925, in disable_logging
	python: stdout/stderr:     if self.is_logged():
	python: stdout/stderr:   File "$HOME/.weechat/python/autoload/otr.py", line 875, in is_logged
	python: stdout/stderr:     buf = self.buffer()
	python: stdout/stderr:   File "$HOME/.weechat/python/autoload/otr.py", line 725, in buffer
	python: stdout/stderr:     nick=self.peer_nick
	python: stdout/stderr: UnicodeEncodeError: 'ascii' codec can't encode characters in position 23-24: ordinal not in range(128)
=!=	python: error in function "command_cb"
```

**Comment by mmb** [comment]
Thanks for reporting this.

I'm not sure how this could happen because the peer server, peer nick and format string should all be unicode.

Is your server name or your peer's nick not ASCII?

Are you using any other Python scripts at the same time?

Is there anything unusual about your python installation or is it just a standard OS package?

**Comment by l2dy** [comment]
@mmb My peer's nick. No other scripts in use. I'm using Python 2.7 from MacPorts.

**Comment by mmb** [comment]
Do you know a public server I could test this on? All the ones I tried did not allow non-ASCII nicks.

**Comment by l2dy** [comment]
> http://ozinger.org/, http://www.hanirc.org/, http://www.luatic.net/, https://twitter.com/HanIRC, etc

See https://github.com/martynsmith/node-irc/issues/456.

**Comment by mmb** [comment]
I was able to reproduce the issue on ozinger.

I'm guessing these servers accept any bytes in any encoding as nicks. weechat-otr expects all strings received from the server to be in utf-8.

We could confirm this with your friend's nick if you are willing to add a debug line to the script and try it.

**Comment by l2dy** [comment]
@mmb You mean otr_debug_buffer or a patch?

**Comment by l2dy** [comment]
I'm willing to help.

**Comment by mmb** [comment]
If you can email the bytes that WeeChat is returning to the script I can look into it. My email is in my GitHub profile.

1. Add this line to the script right before line 419: It should be right before the last line in the function `buffer_get_string`.
```
debug(('buffer_get_string', prop, weechat.buffer_get_string(encoded_buf, PYVER.to_str(prop)).encode('hex')))
```

2. turn on OTR debugging in Weechat with `/set otr.general.debug on`

3. reproduce the issue and then check the OTR debug buffer for something that looks like `(u'buffer_get_string', u'localvar_channel', '<a bunch of hex digits>` and send me those digits.

Thanks!

**Comment by mmb** [comment]
@l2dy Can you try the latest master of the script and let me know if this is still happening?

**Comment by l2dy** [comment]
Fix verified on irc.luatic.net
